require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/companies", type: :request do
  before do
    Company.destroy_all
    FactoryBot.create_list(:company, 5)
    FactoryBot.create(:contabil_sef)
  end

  let(:contabil_sef) { User.contabil_sef.first }

  
  describe "GET /index" do
    it "renders a successful response" do
      get api_v1_companies_url, headers: authenticated_header(contabil_sef)
      expect(response).to be_successful
      expect(json.size).to eq(5)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      company = Company.first
      get api_v1_company_url(company), headers: authenticated_header(contabil_sef)
      expect(response).to be_successful
      expect(json['name']).to eq(company.name)
    end
  end
end
