require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
    before do
      @user = FactoryBot.create(:patron)
    end
  
  let(:valid_attributes) {
    {email: @user.email, password: '12345678'}
  }

  let(:invalid_attributes) {
    {email: @user.email, password: 'wrongpassword'}
  }


  describe "POST /users/sign_in" do
    context "with valid parameters" do
      it "authentificates a user" do
        post '/users/sign_in', params: { user: valid_attributes }
        expect(response).to be_successful
      end
    end

    context "with invalid parameters" do
      it "throws error when User sign_in params are invalid" do
        post '/users/sign_in', params: { user: invalid_attributes }
        expect(response).to be_unauthorized
      end
    end
  end

  describe "DELETE /users/sign_out" do
    it "disconnects a user" do
        delete '/users/sign_out', headers: authenticated_header(@user)
        expect(response).to be_successful
    end
  end

end
