default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  host: localhost
  username: postgres
  password: 123

development:
  <<: *default
  database: conta_development

test:
  <<: *default
  database: conta_test

production:
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>